name: Pulumi

on:
  push:
    branches:
      - main

jobs:
  preview:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install .NET Core SDK"
        uses: actions/setup-dotnet@v1.9.0
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: development
          work-dir: Source/Ummati.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
